services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  payment:
    depends_on:
      postgres:
        condition: service_healthy
    build: ../../payment/
    environment:
      PAYMENT_PORT: "9090"
      ENV: development
      DATA_SOURCE_URL: >
        host=postgres user=payments password=pass dbname=payments
        port=5432 sslmode=disable TimeZone=UTC

  order:
    depends_on:
      postgres:
        condition: service_healthy
    build: ../../order/
    ports:
      - "8181:8181"
    environment:
      APPLICATION_PORT: "8181"
      ENV: development
      DATA_SOURCE_URL: >
        host=postgres user=orders password=pass dbname=orders
        port=5432 sslmode=disable TimeZone=UTC
      PAYMENT_SERVICE_URL: payment:9090